### ISSUE TITLE
Compile-time parsing

### ISSUE THREAD

**Issue by mjhopkins** [scalasyd/scalasyd#86]
Sometimes, rather than constructing a domain object in code, it's clearer to specify it as YAML or JSON.

But at the same time, we don't want to give up the compile-time guarantees we get from a programming language, as this would expose us to runtime errors if we made a mistake in the YAML/JSON.

Imagine if we could write the following, and have it checked at compile time:

```
val order1: Order =
  order"""
    order-ref: RJ24551
    customer-id: 9993
    items:
    - quantity: 1
      product:
        name: spanner
        code: 23599
        dept: hardware
        unit-price: 19.50
    - quantity: 3
      product:
        name: potting mix
        code: 18563
        dept: garden
        unit-price: 12.99
  """
```

We can, through the power of macros!

I'll show step-by-step how to build up an implementation of the above.
Key ingredients will be
* macros that produce macros
* string interpolators
* compile-time evaluation
